# 服务器端口
server:
  port: 8090
  servlet:
    # 定义路径
    context-path: /api

spring:

  # 需要将其设置为always，彩色打印日志
  output:
    ansi:
      enabled: always
  #  测试
  #  security:
  #    user:
  #      name: user
  #      password: user
  main:
    banner-mode: off # 禁止控制台打印出banner
    allow-circular-references: true # 允许循环依赖
  datasource: # 数据库配置
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/contest_web?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: root
      test-while-idle: false # 取消空闲时测试连接的有效性

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 全局默认主键类型
    banner: false # 关闭banner
  configuration:
    # MP日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名

mybatis-plus-join:
  banner: false # 关闭banner